#!/bin/bash
#===============================================================================
#titulo          :infolinux
#descrição       :Script para capturar informações básicas do Linux
#autor           :Cleber S Leite ( clebersleite@gmail.com )
#data            :14/12/2015
#versão          :1.0    
#uso             :infolinux
#notas           :Precisa do comando CURL.
#licença         :GPL3
#Observação      :Caso o script apresente erro de caractere,use o comando: 
#                 dos2unix NOME_DO_SCRIPT 
#                 para corrigir 
#===============================================================================
 
if [ "$(id -u)" != "0" ]; then
   echo " "
   echo "Você precisa rodar este script como super usuário!" 1>&2
   echo " "
   exit 1
fi
 
if which curl > /dev/null; then
    echo ""
else
    echo ""
    echo "É Necessário o comando CURL"
    echo ""
    exit 1
fi
 
echo ""
echo "Informações do Linux:"
echo "========================"
echo ""
echo "CPU:"
echo -e "\033[1;33m" $(cat /proc/cpuinfo | grep "model name" | head -1 | cut -c 14-100) "\033[0m"
echo "Processadores:"
echo -e "\033[1;33m" $(cat /proc/cpuinfo | grep processor | wc -l) "\033[0m"
echo "Memória Total:"
memoria=$(free -m | grep Mem | awk {'print $2'})
echo -e "\033[1;33m" $(expr  $memoria / 1024)Gb "\033[0m"
echo "Uptime"
echo -e "\033[1;33m" $(uptime | cut -d " " -f 4,5 | sed 's/.$//') "\033[0m"
echo "Distribuição: "
if [ -f "/etc/redhat-release" ]
then
     echo -e "\033[1;33m" $(cat /etc/redhat-release | head -1 | cut -d "=" -f 2) "\033[0m"
else
     echo -e "\033[1;33m" $(cat /etc/lsb-release | head -1 | cut -d "=" -f 2) "\033[0m"
fi
echo "Versão do Kernel:"
echo -e "\033[1;33m" $(uname -r) "\033[0m"
echo "Pacotes instalados:"
if [ -f "/etc/redhat-release" ]
then
      echo -e "\033[1;33m" $(rpm -qa | wc -l) "\033[0m"
else
      echo -e "\033[1;33m" $(dpkg -l | wc -l) "\033[0m"
fi
echo "Espaço em disco:"
disco=`df -m | grep '/$' | cut -d ' ' -f 1 | cut -c -8`
if [ -f "/etc/redhat-release" ]
then
     echo -e "\033[1;33m" $(fdisk -l $disco | head -2 | cut -d " " -f 3,4 | sed 's/.$//') "\033[0m"
else
     echo -e "\033[1;33m" $(fdisk -l $disco | head -1 | cut -d " " -f 3,4 | sed 's/.$//') "\033[0m"
fi
echo "Usuários do sistema:"
echo -e "\033[1;33m" $(awk -F'[/:]' '{if ($3 >= 1000 && $3 != 65534) print $1}' /etc/passwd) "\033[0m"
echo "IP: "
echo -e "\033[1;33m" $(ip route get 8.8.8.8| grep src| sed 's/.*src \(.*\)$/\1/g') "\033[0m"
echo "Gateway:"
echo -e "\033[1;33m" $(ip route | awk '/default/ { print $3 }') "\033[0m"
echo "DNS: "
echo -e "\033[1;33m" $(cat /etc/resolv.conf | grep nameserver | awk '{print $2}') "\033[0m"
echo "IP Externo:"
echo -e "\033[1;33m" $(curl -sS http://whatismyip.akamai.com/) "\033[0m"
echo
